local palette = require('joyous-wilds.palette')
local config = require('joyous-wilds.config')

-- local sym = injected_functions.sym

local groups = {
  -- Highlight groups, see :h highlight-groups
  ColorColumn = {fg = nil, bg = palette.bg},
  Conceal = {fg = palette.gray_3, bg = nil},
  CurSearch = {fg = nil, bg = palette.ochre},
  Cursor = {fg = palette.bg, bg = palette.fg},
  lCursor = {fg = palette.bg, bg = palette.fg},
  CursorIM = {fg = palette.bg, bg = palette.fg},
  CursorColumn = {fg = nil, bg = palette.bg},
  CursorLine = {fg = nil, bg = palette.bg},
  Directory = {fg = palette.fg, bg = nil},
  DiffAdd = {fg = nil, bg = palette.info_bg},
  DiffChange = {fg = nil, bg = palette.info_bg},
  DiffDelete = {fg = nil, bg = palette.error_bg},
  DiffText = {fg = nil, bg = palette.info_bg},
  EndOfBuffer = {fg = palette.bg, bg = nil},
  TermCursor = {fg = palette.bg, bg = palette.fg},
  TermCursorNC = {fg = palette.bg, bg = palette.fg},
  ErrorMsg = {fg = palette.red, bg = palette.bg, bold = true},
  WinSeparator = {fg = palette.jw_green_3, bg = nil, bold = true},
  Folded = {fg = palette.fg, bg = palette.blue_4},
  FoldColumn = {fg = palette.gray_6, bg = nil},
  SignColumn = {fg = nil, bg = palette.bg},
  IncSearch = {fg = nil, bg = palette.blue_4},
  Substitute = {fg = nil, bg = palette.blue_4},
  LineNr = {fg = palette.gray_4, bg = nil},
  LineNrAbove = {fg = nil, bg = palette.bg},
  LineNrBelow = {fg = nil, bg = palette.bg},
  CursorLineNr = {fg = palette.gray_3, bg = nil, bold = true},
  CursorLineFold = {fg = nil, bg = palette.bg},
  CursorLineSign = {fg = nil, bg = palette.bg},
  MatchParen = {fg = nil, bg = palette.blue_4},
  ModeMsg = {fg = palette.fg, bg = palette.bg},
  MsgArea = {fg = palette.fg, bg = palette.bg},
  MsgSeparator = {fg = palette.fg, bg = palette.bg},
  MoreMsg = {fg = palette.gray_4, bg = nil},
  NonText = {fg = palette.gray_5, bg = nil},
  Normal = {fg = palette.fg, bg = palette.bg},
  NormalFloat = {fg = palette.fg, bg = palette.bg},
  FloatBorder = {fg = palette.jw_green_1, bg = palette.bg, bold=true},
  FloatTitle = {fg = palette.white, bg = palette.bg},
  NormalNC = {fg = palette.fg, bg = palette.bg},
  Pmenu = {fg = palette.fg, bg = palette.bg},
  PmenuSel = {fg = nil, bg = palette.blue_4},
  PmenuKind = {fg = nil, bg = palette.bg},
  PmenuKindSel = {fg = nil, bg = palette.bg},
  PmenuExtra = {fg = nil, bg = palette.bg},
  PmenuExtraSel = {fg = nil, bg = palette.bg},
  PmenuSbar = {fg = nil, bg = palette.bg},
  PmenuThumb = {fg = nil, bg = palette.gray_3},
  Question = {fg = palette.gray_4, bg = nil},
  QuickFixLine = {fg = nil, bg = palette.blue_4},
  Search = {fg = nil, bg = palette.ochre},
  SpecialKey = {fg = palette.blue_2, bg = nil, bold = true},
  SpellBad = {fg = nil, bg = nil, sp = palette.red, undercurl = true},
  SpellCap = {fg = nil, bg = nil, sp = palette.straw, undercurl = true},
  SpellLocal = {fg = nil, bg = nil, sp = palette.green, underline = true},
  SpellRare = {fg = nil, bg = nil, sp = palette.pink, underline = true},
  StatusLine = {fg = palette.fg, bg = palette.bg},
  StatusLineNC = {fg = palette.bg, bg = palette.bg},
  TabLine = {fg = palette.gray_3, bg = palette.bg},
  TabLineFill = {fg = palette.fg, bg = palette.bg},
  TabLineSel = {fg = palette.fg, bg = palette.bg},
  Title = {fg = palette.fg, bg = nil, bold = true},
  Visual = {fg = nil, bg = palette.blue_4},
  VisualNOS = {fg = nil, bg = palette.bg},
  WarningMsg = {fg = palette.coral, bg = palette.bg},
  Whitespace = {fg = palette.gray_4, bg = nil},
  WildMenu = {fg = palette.fg, bg = palette.blue_2},
  WinBar = {fg = palette.gray_2, bg = palette.bg},
  WinBarNC = {fg = palette.bg, bg = palette.bg},

  -- Status line
  -- Menu
  -- Scrollbar
  -- Tooltip

  -- Syntax groups, see :h group-name
  Comment = {fg = palette.green_2, bg = nil},

  Constant = {fg = palette.blue_2, bg = nil},
  String = {fg = palette.coral, bg = nil},
  Character = {fg = palette.coral, bg = nil},
  Number = {fg = palette.green_1, bg = nil},
  Boolean = {fg = palette.blue_3, bg = nil},
  Float = {fg = palette.green_1, bg = nil},

  Identifier = {fg = palette.blue_1, bg = nil},
  Function = {fg = palette.straw, bg = nil},

  Statement = {fg = palette.fg, bg = nil},
  Conditional = {fg = palette.pink, bg = nil},
  Repeat = {fg = palette.pink, bg = nil},
  Label = {fg = palette.blue_1, bg = nil},
  Operator = {fg = palette.fg, bg = nil},
  Keyword = {fg = palette.pink, bg = nil},
  Exception = {fg = palette.pink, bg = nil},

  PreProc = {fg = palette.pink, bg = nil},
  Include = {fg = palette.pink, bg = nil},
  Define = {fg = palette.pink, bg = nil},
  Macro = {fg = palette.blue_3, bg = nil},
  PreCondit = {fg = palette.blue_3, bg = nil},

  Type = {fg = palette.blue_3, bg = nil},
  StorageClass = {fg = palette.blue_1, bg = nil},
  Structure = {fg = palette.turquoise, bg = nil},
  Typedef = {fg = palette.turquoise, bg = nil},

  Special = {fg = palette.coral, bg = nil},
  SpecialChar = {fg = palette.coral, bg = nil},
  Tag = {fg = palette.blue_3, bg = nil},
  Delimiter = {fg = palette.fg, bg = nil},
  SpecialComment = {fg = palette.fg, bg = nil},
  Debug = {fg = palette.red, bg = nil},

  Underlined = {fg = nil, bg = nil, underline = true},
  Ignore = {fg = nil, bg = nil},
  Error = {fg = palette.error, bg = nil},
  Todo = {fg = palette.ecru, bg = nil},

  -- Neovim LSP
  LspReferenceText = {fg = palette.gray_3, bg = nil},
  LspReferenceRead = {fg = palette.gray_3, bg = nil},
  LspReferenceWrite = {fg = palette.gray_3, bg = nil},
  LspCodeLens = {fg = palette.gray_3, bg = nil},
  LspCodeLensSeparator = {fg = palette.gray_3, bg = nil},
  LspSignatureActiveParameter = {fg = palette.gray_3, bg = nil},

  -- Diagnostics
  -- DiagnosticError = {fg = nil, bg = nil},
  -- DiagnosticWarn = {fg = nil, bg = nil},
  -- DiagnosticInfo = {fg = nil, bg = nil},
  -- DiagnosticHint = {fg = nil, bg = nil},
  -- DiagnosticOk = {fg = nil, bg = nil},
  -- DiagnosticVirtualTextError = {fg = nil, bg = nil},
  -- DiagnosticVirtualTextWarn = {fg = nil, bg = nil},
  -- DiagnosticVirtualTextInfo = {fg = nil, bg = nil},
  -- DiagnosticVirtualTextHint = {fg = nil, bg = nil},
  -- DiagnosticVirtualTextOk = {fg = nil, bg = nil},
  -- DiagnosticUnderlineError = {fg = nil, bg = nil},
  -- DiagnosticUnderlineWarn = {fg = nil, bg = nil},
  -- DiagnosticUnderlineInfo = {fg = nil, bg = nil},
  -- DiagnosticUnderlineHint = {fg = nil, bg = nil},
  -- DiagnosticUnderlineOk = {fg = nil, bg = nil},
  -- DiagnosticFloatingError = {fg = nil, bg = nil},
  -- DiagnosticFloatingWarn = {fg = nil, bg = nil},
  -- DiagnosticFloatingInfo = {fg = nil, bg = nil},
  -- DiagnosticFloatingHint = {fg = nil, bg = nil},
  -- DiagnosticFloatingOk = {fg = nil, bg = nil},
  -- DiagnosticSignError = {fg = nil, bg = nil},
  -- DiagnosticSignWarn = {fg = nil, bg = nil},
  -- DiagnosticSignInfo = {fg = nil, bg = nil},
  -- DiagnosticSignHint = {fg = nil, bg = nil},
  -- DiagnosticSignOk = {fg = nil, bg = nil},
  -- DiagnosticDeprecated = {fg = nil, bg = nil},
  DiagnosticUnnecessary = {fg = palette.gray_3, bg = nil},

  -- Treesitter
  -- ["@text.literal"] = {fg = nil, bg = nil},
  -- ["@text.reference"] = {fg = nil, bg = nil},
  -- ["@text.title"] = {fg = nil, bg = nil},
  -- ["@text.uri"] = {fg = nil, bg = nil},
  -- ["@text.underline"] = {fg = nil, bg = nil},
  -- ["@text.todo"] = {fg = nil, bg = nil},

  -- ["@comment"] = {fg = nil, bg = nil},
  -- ["@punctuation"] = {fg = nil, bg = nil},
  ["@punctuation.bracket"] = { fg=palette.mustard, bg=nil },

  -- ["@constant"] = {fg = nil, bg = nil},
  -- ["@constant.builtin"] = {fg = palette.red, bg = nil},
  -- ["@constant.macro"] = {fg = palette.red, bg = nil},
  -- ["@define"] = {fg = palette.red, bg = nil},
  -- ["@macro"] = {fg = palette.red, bg = nil},
  -- ["@string"] = {fg = nil, bg = nil},
  -- ["@string.escape"] = {fg = nil, bg = nil},
  -- ["@string.special"] = {fg = nil, bg = nil},
  -- ["@character"] = {fg = nil, bg = nil},
  -- ["@character.special"] = {fg = nil, bg = nil},
  -- ["@number"] = {fg = nil, bg = nil},
  -- ["@boolean"] = {fg = nil, bg = nil},
  -- ["@float"] = {fg = nil, bg = nil},

  -- ["@function"] = {fg = nil, bg = nil},
  ["@function.builtin"] = {fg = nil, bg = nil},
  -- ["@function.macro"] = {fg = palette.red, bg = nil},
  -- ["@parameter"] = {fg = nil, bg = nil},
  -- ["@method"] = {fg = nil, bg = nil},
  -- ["@field"] = {fg = nil, bg = nil},
  -- ["@property"] = {fg = nil, bg = nil},
  -- ["@constructor"] = {fg = nil, bg = nil},

  -- ["@conditional"] = {fg = nil, bg = nil},
  -- ["@repeat"] = {fg = nil, bg = nil},
  -- ["@label"] = {fg = nil, bg = nil},
  -- ["@operator"] = {fg = nil, bg = nil},
  -- ["@keyword"] = {fg = nil, bg = nil},
  ["@keyword.function"] = {fg = palette.blue_3, bg = nil},
  ["@keyword.modifier"] = {link="Type"},
  ["@keyword.type"] = {link="Type"},
  -- ["@exception"] = {fg = nil, bg = nil},

  ["@variable"] = {fg = palette.blue_1, bg = nil},
  -- ["@type"] = {link="Type"},
  ["@type.builtin"] = {link="Type"},
  ["@type.builtin.python"] = {fg = palette.turquoise, bg = nil},
  -- ["@type.definition"] = {fg = nil, bg = nil},
  -- ["@storageclass"] = {fg = nil, bg = nil},
  -- ["@structure"] = {fg = nil, bg = nil},
  -- ["@namespace"] = {fg = nil, bg = nil},
  -- ["@include"] = {fg = palette.red, bg = nil},
  -- ["@preproc"] = {fg = palette.red, bg = nil},
  -- ["@debug"] = {fg = nil, bg = nil},
  -- ["@tag"] = {fg = nil, bg = nil},

  ["@lsp.mod.constructorOrDestructor.cpp"] = { fg=palette.straw, bg=nil },
  ["@lsp.type.class"] = {fg = palette.turquoise, bg = nil},
  ["@lsp.type.type"] = {fg = palette.turquoise, bg = nil},

  WhichKey = {fg = palette.jw_pink_1},
  -- WhichKeyBorder = {fg = nil},
  WhichKeyDesc = {fg = palette.fg},
  WhichKeyGroup = {fg = palette.blue_2},
  -- WhichKeyIcon = {fg = nil},
  -- WhichKeyIconAzure = {fg = nil},
  -- WhichKeyIconBlue = {fg = nil},
  -- WhichKeyIconCyan = {fg = nil},
  -- WhichKeyIconGreen = {fg = nil},
  -- WhichKeyIconGrey = {fg = nil},
  -- WhichKeyIconOrange = {fg = nil},
  -- WhichKeyIconPurple = {fg = nil},
  -- WhichKeyIconRed = {fg = nil},
  -- WhichKeyIconYellow = {fg = nil},
  -- WhichKeyNormal = {fg = nil},
  WhichKeySeparator = {fg = palette.white},
  -- WhichKeyTitle = {fg = nil},
  -- WhichKeyValue = {fg = nil},

  -- NvimTree
  NvimTreeRootFolder = {fg = palette.fg},
  NvimTreeSpecialFile = {fg = palette.blue_1},
  NvimTreeFolderIcon = {fg = palette.folder},
  NvimTreeOpenedFolderIcon = {fg = palette.folder_open},
  NvimTreeFolderArrowClosed = {fg = palette.white},
  NvimTreeFolderArrowOpen = {fg = palette.white},

  -- NvimTree GIT icon highlights
  NvimTreeGitDeletedIcon = {fg = palette.git_red_dark},
  NvimTreeGitDirtyIcon = {fg = palette.git_coral_dark},
  NvimTreeGitIgnoredIcon = {fg = palette.gray_3},
  NvimTreeGitMergeIcon = {fg = palette.git_red_dark},
  NvimTreeGitNewIcon = {fg = palette.git_green_dark},
  NvimTreeGitRenamedIcon = {fg = palette.git_green_dark},
  NvimTreeGitStagedIcon = {fg = palette.git_blue_dark},

  -- NvimTree GIT file highlights
  NvimTreeGitFileDeletedHL = {fg = palette.git_red},
  NvimTreeGitFileDirtyHL = {fg = palette.git_coral},
  NvimTreeGitFileIgnoredHL = {fg = palette.gray_3},
  NvimTreeGitFileMergeHL = {fg = palette.git_red},
  NvimTreeGitFileNewHL = {fg = palette.git_green},
  NvimTreeGitFileRenamedHL = {fg = palette.git_green},
  NvimTreeGitFileStagedHL = {fg = palette.git_blue},

}

return groups
